import {
  User,
  JourneyPhase,
  Theme,
  JourneyEntry,
  CalendarEvent,
  ResourceItem,
  BeforeNowShift,
  SchoolSignal,
  DossierChapter,
  CEQHSReviewCheckpoint,
} from './types';

export const JOURNEY_PHASES: JourneyPhase[] = [
  {
    id: '01_EXPLORE',
    number: '01',
    name: 'EXPLORE',
    question: 'Where are we now?',
    description: 'School context, personal intention, baseline reflection, listening, observation and orientation.',
  },
  {
    id: '02_FOCUS',
    number: '02',
    name: 'FOCUS',
    question: 'What matters now?',
    description: 'Selected themes, school priorities, individual intentions, professional learning, practice invitations.',
  },
  {
    id: '03_PRACTISE',
    number: '03',
    name: 'PRACTISE',
    question: 'What are we trying?',
    description: 'Classroom practice, educator experiments, team practice, ACT and EAR practice cycles.',
  },
  {
    id: '04_EMBED',
    number: '04',
    name: 'EMBED',
    question: 'What is becoming part of how we work?',
    description: 'Routines, shared language, school practices, leadership rituals, and resilient classroom culture.',
  },
  {
    id: '05_REFLECT',
    number: '05',
    name: 'REFLECT',
    question: 'What are we noticing?',
    description: 'Personal reflection, teacher voice, student voice, colleague observations, school-wide reflections.',
  },
  {
    id: '06_REVIEW',
    number: '06',
    name: 'REVIEW',
    question: 'What have we learned?',
    description: 'Evidence synthesis, school-wide review, CEQHS dialogue, and authentic developmental verification.',
  },
  {
    id: '07_RENEW',
    number: '07',
    name: 'RENEW',
    question: 'What continues?',
    description: 'Next priorities, future intentions, practices worth sustaining, and next year’s direction.',
  },
];

export const MOCK_USERS: Record<string, User> = {
  maya: {
    id: 'maya',
    name: 'Maya Lin',
    email: 'maya.lin@stjude.edu',
    role: 'educator',
    schoolId: 'st_jude',
    schoolName: 'St. Jude Academy',
    academicYear: '2026–27',
    title: 'Grade 7 Humanities & Advisory Lead',
    intention: 'I want to listen without immediately trying to solve, and notice my own emotional triggers before correcting students.',
    intentionDate: '12 September 2026',
    reflectionMirror: {
      earlyReflection: 'I tend to interpret silence or sudden withdrawal as disengagement or defiance. When pressed for time, I step in with answers.',
      earlyDate: '24 September 2026',
      prompt: 'You wrote this at the start of your journey. What are you noticing about student silence now in your classroom?',
    },
  },
  marcus: {
    id: 'marcus',
    name: 'Marcus Chen',
    email: 'marcus.chen@stjude.edu',
    role: 'educator',
    schoolId: 'st_jude',
    schoolName: 'St. Jude Academy',
    academicYear: '2026–27',
    title: 'Grade 9 Science & STEM Coordinator',
    intention: 'I want to create space where failure in laboratory experiments is greeted with emotional safety rather than anxiety.',
    intentionDate: '15 September 2026',
  },
  elena: {
    id: 'elena',
    name: 'Elena Rostova',
    email: 'e.rostova@stjude.edu',
    role: 'coordinator',
    schoolId: 'st_jude',
    schoolName: 'St. Jude Academy',
    academicYear: '2026–27',
    title: 'Vice Principal & CEQHS School Coordinator',
  },
  aris: {
    id: 'aris',
    name: 'Dr. Aris Thorne',
    email: 'aris.thorne@ceqhs.org',
    role: 'admin',
    schoolId: 'st_jude',
    schoolName: 'St. Jude Academy',
    academicYear: '2026–27',
    title: 'CEQHS Senior Programme Lead & Journey Anchor',
  },
};

export const THEMES: Theme[] = [
  {
    id: 'empathetic-discipline',
    title: 'Empathetic Discipline',
    question: 'Can I understand before I respond?',
    category: 'Relational Safety',
    tagline: 'Moving from reactive sanctioning to intentional, curious connection.',
    overview:
      'Empathetic Discipline asks educators to pause at the exact moment instinct urges them to impose immediate compliance. When student behaviour disrupts our intended flow, curiosity rather than control becomes our primary instrument.',
    whyItMatters:
      'Punitive reactions reinforce nervous system dysregulation for both student and teacher. By regulating ourselves first and seeking to comprehend the underlying distress, we preserve relational trust while upholding necessary boundaries.',
    practiseSteps: [
      '1. Notice your bodily reaction (tightened jaw, quickened breath).',
      '2. Pause: take one conscious exhale before speaking.',
      '3. Get curious: ask one non-accusatory question.',
      '4. Respond intentionally with collaborative dignity.',
    ],
    reflectPrompt: 'What changed when you changed your response? What surprised you about the student’s unspoken state?',
    evidenceIdeas: [
      'Student self-regulation debrief sheet',
      'Audio reflection after a de-escalation',
      'Classroom transition agreement photo',
      'Journal entry on an interrupted reaction',
    ],
    relatedPractices: ['Triggered Teacher', 'De-escalating Dynamics', 'Belonging in Conflict'],
  },
  {
    id: 'triggered-teacher',
    title: 'Triggered Teacher',
    question: 'What is this reaction telling me about my own boundary?',
    category: 'Self-Awareness',
    tagline: 'Recognizing our personal emotional flashpoints and reclaiming agency.',
    overview:
      'Every educator has unexamined triggers—defiance, apathy, disorganization, or perceived disrespect. This theme explores how adult emotional competence precedes student emotional regulation.',
    whyItMatters:
      'A dysregulated adult cannot regulate a dysregulated child. When we understand our emotional triggers as historical data rather than immediate threats, we model genuine psychological maturity.',
    practiseSteps: [
      '1. Name the sensation internally: "I am feeling challenged or unseen."',
      '2. Anchor physically: feel both feet rooted on the floor.',
      '3. De-couple the student from the trigger: "This is not about me."',
      '4. Choose the quietest possible next intervention.',
    ],
    reflectPrompt: 'Which student behaviour most easily pulls you out of calm? Where does that reaction live in your body?',
    evidenceIdeas: [
      'Personal field note after high-stress period',
      'Reflective voice memo recorded during planning period',
      'Colleague debrief observation',
    ],
    relatedPractices: ['Empathetic Discipline', 'The Micro-Pause', 'Adult Emotional Regulation'],
  },
  {
    id: 'belonging-agency',
    title: 'Psychological Belonging',
    question: 'Who is silent in our room, and why?',
    category: 'Classroom Culture',
    tagline: 'Ensuring every student feels valued, heard, and genuinely safe to risk vulnerability.',
    overview:
      'Belonging is not simply being invited into a space; it is the certainty that your presence matters and that mistakes do not diminish your membership in the community.',
    whyItMatters:
      'Without psychological safety, human brains allocate cognitive resources to threat detection rather than creative synthesis or authentic inquiry.',
    practiseSteps: [
      '1. Track who speaks and who retreats across 3 class sessions.',
      '2. Introduce low-stakes anonymous thinking invitations.',
      '3. Validate tentative contributions with quiet affirmation.',
      '4. Protect vulnerable errors as essential learning milestones.',
    ],
    reflectPrompt: 'What implicit signals does our room send about who belongs and what kind of intellect is praised?',
    evidenceIdeas: [
      'Student voice feedback cards',
      'Classroom discourse map (speaking flow)',
      'Photograph of collaborative norms co-created with students',
    ],
    relatedPractices: ['Student Agency', 'Listening Circles', 'Shared Classroom Agreements'],
  },
  {
    id: 'student-agency',
    title: 'Cultivating Student Agency',
    question: 'Where can I step back so they can step forward?',
    category: 'Empowerment',
    tagline: 'Transferring ownership of thinking, problem-solving, and emotional repair.',
    overview:
      'Teachers often solve problems students are fully equipped to navigate with guided scaffolding. Agency grows when adults resist the urge to provide immediate answers.',
    whyItMatters:
      'Real-world emotional resilience develops when young people actively negotiate peer conflict, evaluate their own thinking, and take genuine responsibility.',
    practiseSteps: [
      '1. Count to 10 silently before answering your own question.',
      '2. Hand peer misunderstandings back to the group with structured prompts.',
      '3. Allow students to co-design learning pacing and reflection intervals.',
    ],
    reflectPrompt: 'When was the last time you let a productive struggle continue without intervening?',
    evidenceIdeas: [
      'Student-led conflict resolution agreement',
      'Peer-to-peer feedback transcripts',
      'Video excerpt of student facilitated circle',
    ],
    relatedPractices: ['Psychological Belonging', 'Empathetic Discipline'],
  },
];

export const INITIAL_ENTRIES: JourneyEntry[] = [
  {
    id: 'entry-1',
    type: 'practice',
    title: 'Waiting before responding during transitions',
    date: '16 September 2026',
    month: 'September 2026',
    phaseId: '03_PRACTISE',
    themeId: 'empathetic-discipline',
    themeTitle: 'Empathetic Discipline',
    authorId: 'maya',
    authorName: 'Maya Lin',
    authorRole: 'Grade 7 Humanities',
    description: 'Tried the 4-second breath pause during the loud midday transition from lunch to history inquiry.',
    whatHappened: 'Class walked in noisy, with two students arguing over lockers. Rather than shouting over the room, I stood by the door and took three audible, grounding breaths.',
    whatDidINotice: 'The students near me noticed the posture and lowered their voices without a command. It took 45 seconds longer to start, but the tension evaporated.',
    whatMightITryNext: 'Involve students in setting the transition music or ritual so the rhythm belongs to them.',
    visibility: 'Dossier',
    includedInDossier: true,
  },
  {
    id: 'entry-2',
    type: 'moment',
    title: 'A student stayed behind to speak',
    date: '21 September 2026',
    month: 'September 2026',
    phaseId: '05_REFLECT',
    themeId: 'belonging-agency',
    themeTitle: 'Psychological Belonging',
    authorId: 'maya',
    authorName: 'Maya Lin',
    authorRole: 'Grade 7 Humanities',
    momentCategory: 'Connection',
    description: 'A student stayed behind after class and told me something they had been afraid to say earlier.',
    whyDoesThisMatter: 'They said: "You didn’t cut off David when he was rambling today, so I figured you wouldn’t judge me." It proved that how we treat one student speaks to all 26 witnesses in the room.',
    visibility: 'Dossier',
    includedInDossier: true,
  },
  {
    id: 'entry-3',
    type: 'reflection',
    title: 'Baseline intention check: Rushing to solutions',
    date: '28 September 2026',
    month: 'September 2026',
    phaseId: '01_EXPLORE',
    themeId: 'triggered-teacher',
    themeTitle: 'Triggered Teacher',
    authorId: 'maya',
    authorName: 'Maya Lin',
    authorRole: 'Grade 7 Humanities',
    description: 'Deep observation of my impulse to fix things when the classroom schedule feels tight.',
    whatHappened: 'During advisory, a student began crying about feeling overwhelmed with projects. My immediate instinct was to open the planner and fix their calendar.',
    whatDidINotice: 'I noticed my own discomfort with their sadness. Fixing was my defensive shield. When I stopped typing and just sat with them, they took a deep breath on their own.',
    whatMightITryNext: 'Practise asking: "Do you need me to listen, to help you brainstorm, or do you just need quiet company right now?"',
    visibility: 'School',
    includedInDossier: true,
  },
  {
    id: 'entry-4',
    type: 'moment',
    title: 'Quiet student volunteered to lead group',
    date: '06 October 2026',
    month: 'October 2026',
    phaseId: '03_PRACTISE',
    themeId: 'belonging-agency',
    themeTitle: 'Psychological Belonging',
    authorId: 'maya',
    authorName: 'Maya Lin',
    authorRole: 'Grade 7 Humanities',
    momentCategory: 'Belonging',
    description: 'Today a student who usually avoids group discussion volunteered to lead the primary source analysis.',
    whyDoesThisMatter: 'I almost moved on because we were short on time, but I decided to let the moment breathe. It reminded me that creating space is more important than completing the lesson plan.',
    visibility: 'Dossier',
    includedInDossier: true,
  },
  {
    id: 'entry-5',
    type: 'voice',
    title: 'Voice debrief after difficult parent conference',
    date: '14 October 2026',
    month: 'October 2026',
    phaseId: '05_REFLECT',
    themeId: 'triggered-teacher',
    themeTitle: 'Triggered Teacher',
    authorId: 'maya',
    authorName: 'Maya Lin',
    authorRole: 'Grade 7 Humanities',
    description: 'Recorded 1 minute voice reflection right after an emotional conference.',
    audioDuration: '01:14',
    transcript: 'Today I realised that I was already tense before the parent even entered the room. I was anticipating being blamed for their child’s missing homework. Because I noticed my tight shoulders, I deliberately unclenched my hands on the desk. When they started aggressively, I didn’t defend. I said: "You love your child deeply and you’re worried." The whole room softened.',
    whyDoesThisMatter: 'Validating the human underneath the frustration dismantles conflict faster than any policy document.',
    visibility: 'Dossier',
    includedInDossier: true,
  },
  {
    id: 'entry-6',
    type: 'evidence',
    title: 'Co-created Classroom Calming Norms',
    date: '22 October 2026',
    month: 'October 2026',
    phaseId: '04_EMBED',
    themeId: 'empathetic-discipline',
    themeTitle: 'Empathetic Discipline',
    authorId: 'maya',
    authorName: 'Maya Lin',
    authorRole: 'Grade 7 Humanities',
    evidenceType: 'Photograph',
    description: 'Photo of the student-drawn regulation anchor poster hung beside the classroom library.',
    photoUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1000&q=80',
    whyDoesThisMatter: 'The words came from Grade 7 students themselves: "When you feel like screaming, take the window seat for 2 minutes." It is now referenced daily by peers without teacher prompting.',
    visibility: 'Dossier',
    includedInDossier: true,
  },
  {
    id: 'entry-7',
    type: 'seen_by_others',
    title: 'Colleague observation: Pacing and student response time',
    date: '04 November 2026',
    month: 'November 2026',
    phaseId: '05_REFLECT',
    themeId: 'empathetic-discipline',
    themeTitle: 'Empathetic Discipline',
    authorId: 'maya',
    authorName: 'Maya Lin',
    authorRole: 'Grade 7 Humanities',
    observedBy: 'Marcus Chen (STEM Lead & Colleague)',
    description: 'Marcus popped into Period 3 for our peer learning rounds.',
    whatHappened: '"I observed Maya wait a full 8 seconds after asking why the protagonist’s fear was justified. Instead of calling on the usual eager students, she smiled gently. Two reluctant boys raised their hands with incredible observations."',
    whyDoesThisMatter: 'This is not a performance rating. It is a genuine mirror showing that our practice is visible and shifting the atmosphere for children.',
    visibility: 'Dossier',
    includedInDossier: true,
  },
  {
    id: 'entry-8',
    type: 'student_voice',
    title: 'What helps you feel comfortable speaking in class?',
    date: '18 November 2026',
    month: 'November 2026',
    phaseId: '05_REFLECT',
    themeId: 'belonging-agency',
    themeTitle: 'Psychological Belonging',
    authorId: 'maya',
    authorName: 'Maya Lin',
    authorRole: 'Grade 7 Humanities',
    studentQuote: '"In other classes, if you get it wrong, people giggle and the teacher moves to someone else. Here, Ms. Lin says: ‘That is an interesting angle, walk me through how your brain got there.’ It makes getting it wrong feel like solving a puzzle instead of dying."',
    gradeLevel: 'Grade 7 Student',
    description: 'Anonymous exit ticket reflection on class safety.',
    whyDoesThisMatter: 'Direct evidence of student vulnerability becoming a catalyst for intellectual bravery.',
    visibility: 'Dossier',
    includedInDossier: true,
  },
];

export const CALENDAR_EVENTS: CalendarEvent[] = [
  {
    id: 'evt-1',
    date: '2026-09-18',
    monthDay: '18 Sept',
    type: 'LEARN',
    title: 'Educator Practice Circle: Regulating the Regulators',
    description: 'Interactive session exploring adult emotional self-awareness and physiological resets before high-friction classroom hours.',
    preparation: 'Bring 1 recorded moment of friction from the past 2 weeks.',
    relatedTheme: 'Triggered Teacher',
    expectedAction: 'Form triad pairs and complete the Trigger Mapping worksheet.',
  },
  {
    id: 'evt-2',
    date: '2026-09-24',
    monthDay: '24 Sept',
    type: 'REFLECT',
    title: 'Reflection Checkpoint: The Autumn Baseline',
    description: 'School-wide reflection window. Educators review their opening personal intentions and record their initial shift observations.',
    preparation: 'Review your initial intention in the Reflection Mirror.',
    relatedTheme: 'Empathetic Discipline',
    expectedAction: 'Submit at least one honest reflection on problem-solving tendencies.',
  },
  {
    id: 'evt-3',
    date: '2026-10-03',
    monthDay: '03 Oct',
    type: 'PRACTISE',
    title: 'Practice Window: The Curious Pause',
    description: 'A two-week collaborative commitment across all grade teams to ask one curious question before issuing any disciplinary sanction.',
    preparation: 'Print or save the "Curious Question Starters" prompt card.',
    relatedTheme: 'Empathetic Discipline',
    expectedAction: 'Log 2 classroom experiments in your personal journal.',
  },
  {
    id: 'evt-4',
    date: '2026-10-08',
    monthDay: '08 Oct',
    type: 'REFLECT',
    title: 'School Review Checkpoint #1 with CEQHS Lead',
    description: 'Dr. Aris Thorne joins St. Jude coordinator team to review emerging school signals, cross-grade patterns, and celebrate authentic breakthroughs.',
    preparation: 'Coordinator synthesizes top 3 emerging patterns from teacher moments.',
    relatedTheme: 'Psychological Belonging',
    expectedAction: 'Curate selected moments into Dossier Chapter 04.',
  },
  {
    id: 'evt-5',
    date: '2026-11-12',
    monthDay: '12 Nov',
    type: 'LEARN',
    title: 'Student Voice Synthesis Workshop',
    description: 'Gathering and respectfully anonymising student perceptions of classroom emotional safety and adult reactions.',
    preparation: 'Collect 10 anonymous student index card reflections.',
    relatedTheme: 'Cultivating Student Agency',
    expectedAction: 'Upload quotes to Dossier Chapter 06: Voices from Our Community.',
  },
];

export const RESOURCE_LIBRARY: ResourceItem[] = [
  {
    id: 'res-1',
    title: 'The Curious Pause: 12 Non-Punitive Question Starters',
    type: 'Classroom Practice',
    theme: 'Empathetic Discipline',
    journeyPhase: '03_PRACTISE',
    role: 'Educators & Specialists',
    readTime: '4 min read',
    summary: 'Concrete language shifts to replace "Why are you doing that?" with non-confrontational invitations that preserve student self-respect.',
    content: `When a student is off-task or agitated, the mammalian instinct is to demand compliance. These 12 prompt alternatives de-escalate tension:
1. "What is taking up your attention right now?"
2. "How much battery power do you feel like you have for this task?"
3. "Walk me through what feels tricky about getting started."
4. "I can see you're carrying something heavy. Do you want to sit near the window or stay with your group?"
5. "Can we pause for 30 seconds so we can both reset?"`,
  },
  {
    id: 'res-2',
    title: 'Facilitating Safe Reflection Circles in Grade 6–10',
    type: 'Facilitation Guide',
    theme: 'Psychological Belonging',
    journeyPhase: '04_EMBED',
    role: 'Advisors & Pastoral Leads',
    readTime: '6 min read',
    summary: 'A step-by-step framework for building circle rituals where reluctant voices speak without fear of peer derision.',
    content: `Circles work only when the adults embody radical neutrality. Key protocols:
- Use a tactile talking piece with modest weight.
- Right to pass without explanation.
- No immediate cross-talk or adult evaluation ("That was so good!"). Let silence hold the thought.
- Close with collective acknowledgment rather than a sermon.`,
  },
  {
    id: 'res-3',
    title: 'Recognizing the Somatic Signature of Adult Triggers',
    type: 'Article',
    theme: 'Triggered Teacher',
    journeyPhase: '01_EXPLORE',
    role: 'All Educators & Leaders',
    readTime: '5 min read',
    summary: 'How physiological awareness in the teacher’s nervous system prevents destructive escalation in classroom disputes.',
    content: `Before you raise your voice, your body has already sounded an alarm: blood pressure shifts, jaw clenches, breathing becomes shallow. By tracking your personal somatic signature, you intervene at the biological level before words leave your mouth.`,
  },
  {
    id: 'res-4',
    title: 'Before & Now Reflection Protocol for Department Teams',
    type: 'Template',
    theme: 'Empathetic Discipline',
    journeyPhase: '05_REFLECT',
    role: 'Coordinators & Department Heads',
    readTime: '3 min read',
    summary: 'A 20-minute department meeting protocol to identify cultural shifts in how staff respond to student distress.',
    content: `Use this 3-column protocol:
Column 1 (Before): What did we reflexively do when students didn't submit work?
Column 2 (Now): What question or diagnostic do we ask first?
Column 3 (Catalysts): Which specific practice or student interaction unlocked this change?`,
  },
];

export const BEFORE_NOW_SHIFTS: BeforeNowShift[] = [
  {
    id: 'shift-1',
    before: 'Teachers often handle behaviour in isolation, viewing non-compliance as personal disrespect.',
    now: 'Teachers increasingly use shared de-escalation language and pause to diagnose underlying dysregulation.',
    catalysts: ['Empathetic Discipline theme cycles', 'Educator Practice Circles', 'Classroom Curious Question protocol'],
    theme: 'Empathetic Discipline',
  },
  {
    id: 'shift-2',
    before: 'Staff meetings focused primarily on administrative logistics, policy enforcement, and calendar deadlines.',
    now: 'Every staff gathering begins with a 5-minute pause for human checking-in and sharing one Moment That Mattered.',
    catalysts: ['Coordinator leadership shift', 'Weekly gentle Monday/Wednesday reflection prompts'],
    theme: 'Adult Emotional Regulation',
  },
  {
    id: 'shift-3',
    before: 'Student discipline was tracked through automated demerits and sudden office referrals.',
    now: 'Students co-author emotional repair agreements with educators, focusing on restitution and restored belonging.',
    catalysts: ['Classroom calming corners', 'Student Voice reflection cards', 'Restorative peer circles'],
    theme: 'Psychological Belonging',
  },
];

export const SCHOOL_SIGNALS: SchoolSignal[] = [
  {
    id: 'sig-1',
    topic: 'Listening & Holding Silence',
    count: 14,
    type: 'reflections',
    note: 'Appearing in 14 teacher reflections across Humanities, Math, and Arts as a transformative classroom breakthrough.',
  },
  {
    id: 'sig-2',
    topic: 'Belonging in Vulnerability',
    count: 9,
    type: 'moments',
    note: 'Celebrated across 9 recorded Moments That Mattered, particularly among previously quiet or disengaged students.',
  },
  {
    id: 'sig-3',
    topic: 'Midday Classroom Transitions',
    count: 8,
    type: 'challenges',
    note: 'Identified as a recurring challenge when moving between high-energy lunch periods and analytical study blocks.',
  },
  {
    id: 'sig-4',
    topic: 'Student Voice in Rule-Making',
    count: 4,
    type: 'voices',
    note: 'Expanding across 4 grade levels, showing student agency in co-designing class norms and calm-down routines.',
  },
];

export const DOSSIER_CHAPTERS: DossierChapter[] = [
  {
    number: '01',
    title: 'Our Starting Point',
    subtitle: 'Where St. Jude Academy began its journey of human connection',
    status: 'Verified',
    summary:
      'In early autumn 2026, our faculty acknowledged that post-pandemic school rhythms were leaving educators emotionally depleted and students quick to react with defensive posturing. Rather than adding more punitive discipline codes, our leadership chose to commit to the CEQHS Living Journey: grounding our campus in emotional competence, authentic listening, and psychological safety.',
    keyInsights: [
      '28 educators established personal development intentions at the opening retreat.',
      'Baseline reflections identified a common tendency to rush to immediate fixes.',
      'School leadership pledged that reflection would never be used as an evaluative scoring metric.',
    ],
  },
  {
    number: '02',
    title: 'The Questions We Chose',
    subtitle: 'Themes that guided our attention and everyday experiments',
    status: 'Curated',
    summary:
      'We centered our collective focus on two primary inquiries: "Can I understand before I respond?" (Empathetic Discipline) and "What is this reaction telling me about my own boundary?" (Triggered Teacher). Later in the winter, we broadened our practice to ask: "Who is silent in our room, and why?"',
    keyInsights: [
      'Empathetic Discipline became our foundational common denominator across Grade 6 through 12.',
      'Faculty met bi-weekly in Educator Practice Circles to debrief friction without judgment.',
    ],
  },
  {
    number: '03',
    title: 'Our Learning',
    subtitle: 'How adult self-awareness preceded classroom regulation',
    status: 'Curated',
    summary:
      'Educators engaged with CEQHS resource modules, somatic calming guides, and non-defensive question starters. We realized that adult nervous system stability is the true invisible curriculum of every classroom.',
    keyInsights: [
      'Over 87 reflective journal entries logged voluntarily by teachers.',
      'Staff embraced the principle: "A dysregulated adult cannot calm a dysregulated child."',
    ],
  },
  {
    number: '04',
    title: 'Practice in Action',
    subtitle: 'Classroom experiments, transitional rituals, and the Curious Pause',
    status: 'Building',
    summary:
      'From 4-second breath pauses before transitioning between classes to replacing demerit warnings with one curious inquiry, teachers brought CEQHS directly into the daily life of classrooms.',
    keyInsights: [
      '12 collective practices piloted across academic and athletic departments.',
      'Classroom calming spaces established in 18 learning environments.',
    ],
  },
  {
    number: '05',
    title: 'Moments That Mattered',
    subtitle: 'The authentic heart of our school year',
    status: 'Curated',
    summary:
      'A collection of 143 human moments captured by educators on Friday afternoons—small stories of apologies made, quiet students finding their voice, and teachers pausing before reacting.',
    keyInsights: [
      'Connection (42%) and Belonging (31%) were the most frequently tagged moments.',
      'Every moment recorded reinforces that small human shifts create massive institutional change.',
    ],
    sampleQuotes: [
      {
        quote: 'A student stayed behind after class and told me something they had been afraid to say earlier. Because I paused, they felt safe.',
        author: 'Maya Lin',
        role: 'Grade 7 Humanities',
      },
      {
        quote: 'I apologized to period 4 today for rushing them. The collective relief in the room was palpable.',
        author: 'Marcus Chen',
        role: 'Grade 9 Science',
      },
    ],
  },
  {
    number: '06',
    title: 'Voices From Our Community',
    subtitle: 'What students, teachers, and school leaders experienced',
    status: 'Building',
    summary:
      'Student exit tickets, voice reflections, and colleague observations reveal an environment where emotional vulnerability is treated as a strength rather than a weakness.',
    keyInsights: [
      'Students reported feeling less anxious about making mistakes during inquiry sessions.',
      'Colleague observations provided supportive mirrors rather than evaluative rubrics.',
    ],
    sampleQuotes: [
      {
        quote: 'In other classes, getting it wrong feels terrifying. Here, our teacher asks how our brain got there. It feels like solving a puzzle instead of dying.',
        author: 'Grade 7 Student',
        role: 'Student Voice Archive',
      },
    ],
  },
  {
    number: '07',
    title: 'What We Are Noticing',
    subtitle: 'Emerging patterns, recurring challenges, and campus signals',
    status: 'Building',
    summary:
      'School coordinators tracked signals rather than test scores. Faculty reflections highlighted dramatic gains in student agency, while spotlighting midday classroom transitions as an area demanding ongoing attention.',
    keyInsights: [
      '14 reflections spotlighted the power of holding silence.',
      'Midday transitions identified for cross-departmental coordination next term.',
    ],
  },
  {
    number: '08',
    title: 'What We Are Embedding',
    subtitle: 'Before & Now shifts that are becoming our permanent culture',
    status: 'Curated',
    summary:
      'The changes at St. Jude Academy are no longer isolated teacher experiments; they are embedding into our institutional fabric. Staff meetings, advisory blocks, and student discipline policies now embody shared emotional intelligence routines.',
    keyInsights: [
      'Shared restorative language replaced reactive demerits campus-wide.',
      'Weekly teacher reflection circles integrated into contracted planning time.',
    ],
  },
  {
    number: '09',
    title: 'What We Learned',
    subtitle: 'Collective reflections on what worked and what remains difficult',
    status: 'Building',
    summary:
      'We learned that cultural change in a school cannot be rushed. It moves at the speed of trust. While some educators embraced vulnerability immediately, others required patient modelling and psychological safety.',
    keyInsights: [
      'Authentic reflection cannot be forced or assigned as homework.',
      'Leadership presence in practice circles established credibility.',
    ],
  },
  {
    number: '10',
    title: 'Our Next Chapter: What Continues?',
    subtitle: 'End with continuity, not completion',
    status: 'Building',
    summary:
      'Development is never "completed." As St. Jude Academy looks forward, we carry forward our commitment to empathetic discipline, expand student-led restorative mediation, and begin our journey into adolescent emotional agency for 2027–28.',
    keyInsights: [
      'Sustaining the Curious Pause across all new incoming educators.',
      'Deepening student-led circle practices in middle and high school grades.',
      'Maintaining our living archive as an ongoing professional field journal.',
    ],
  },
];

export const CEQHS_REVIEW_CHECKPOINTS: CEQHSReviewCheckpoint[] = [
  {
    id: 'chk-1',
    date: '28 September 2026',
    reviewerName: 'Dr. Aris Thorne (CEQHS Anchor Team)',
    milestone: 'Orientation & Baseline Intentions Verified',
    status: 'Completed',
    stage: 'Observe',
    notes: 'St. Jude Academy demonstrated exceptional authenticity in faculty intentions. Rather than generic compliance goals, educators focused candidly on their personal emotional flashpoints.',
    strengthsObserved: [
      '28 out of 28 educators authored personal development intentions.',
      'Leadership explicitly guaranteed psychological safety for private reflections.',
    ],
    inquiriesForSchool: [
      'How will grade-level teams support each other when autumn workload escalates?',
    ],
  },
  {
    id: 'chk-2',
    date: '20 November 2026',
    reviewerName: 'Dr. Aris Thorne (CEQHS Anchor Team)',
    milestone: 'Mid-Year Practice & Evidence Synthesis',
    status: 'Completed',
    stage: 'Understand',
    notes: 'Review of classroom moments and student voice entries shows deep fidelity to Empathetic Discipline. The transition from punitive demerits to collaborative inquiry is palpable in the field notes.',
    strengthsObserved: [
      'Over 140 Moments That Mattered recorded voluntarily.',
      'Strong integration of student voice confirming lowered anxiety.',
    ],
    inquiriesForSchool: [
      'Consider how specialist teachers (PE, Music, Arts) can share their unique transition practices with core academic faculty.',
    ],
  },
  {
    id: 'chk-3',
    date: '15 February 2027',
    reviewerName: 'Dr. Aris Thorne (CEQHS Anchor Team)',
    milestone: 'School-Level Embedding & Dossier Verification',
    status: 'In Progress',
    stage: 'Reflect',
    notes: 'Coordination team is successfully curating the 10 dossier chapters. The Before & Now shifts represent verified institutional evolution.',
    strengthsObserved: [
      'Before & Now shifts evidence durable changes in staff meeting rituals and restorative agreements.',
    ],
    inquiriesForSchool: [
      'Ensure Chapter 10 focuses on continuity rather than celebrating false completion.',
    ],
  },
];
